app/books/forms.py
from datetime import date
from flask_wtf import FlaskForm
from wtforms import StringField, DateField, TextAreaField, SubmitField, DateTimeField, FileField
from wtforms.validators import DataRequired, Optional

class BookForm(FlaskForm):
    title = StringField('Book Title', validators=[DataRequired()])
    author = StringField('Author', validators=[DataRequired()])
    publication_date = DateTimeField('Publication Date', format='%m/%d/%Y', validators=[Optional()])
    description = TextAreaField('Description')
    cover_img = FileField('Cover Image')



    



    

app/__init__.py
from flask import current_app, Flask
from config import DevelopmentConfig


def create_app(config=DevelopmentConfig):
    """Create an application instance with the desired configuration.

    Also where extentions and blueprints are registerd with the instance
    """
    # Create the application instance and load the desired configuration
    app = Flask(__name__)
    app.config.from_object(config)

    # Register Blueprints
    from app.books.routes import bp as books_bp
    from app.auth.routes import bp as auth_bp

    app.register_blueprint(books_bp)
    app.register_blueprint(auth_bp)
    # Register Extensions

    # Test route
    @app.route('/hello')
    def hello():
        return 'Hello, Flask!'
    
    return app
        

app/books/routes.py
import os
from flask import Blueprint, session, jsonify, render_template, request, redirect, url_for, jsonify, current_app
from werkzeug.utils import secure_filename
from .forms import BookForm
import firestore
from datetime import datetime
import storage



bp = Blueprint('books', __name__)

def clean_form_data(data):
    if 'csrf_token' in data:
        del data['csrf_token']
    if 'submit' in data:
        del data['submit']
    return data

def upload_image_file(img):
    """
    Upload the user-uploaded file to Google Cloud Storage and retrieve its
    publicly-accessible URL.
    """
    if not img:
        return None

    public_url = storage.upload_file(
        img.read(),
        img.filename,
        img.content_type
    )

    current_app.logger.info(
        'Uploaded file %s as %s.', img.filename, public_url)
    print(f'public_url: {public_url}')
    return public_url


@bp.route('/', methods=['GET', 'POST'])
def index():
    """Load feed of all books for user
    
    Handles AJAX POST requests for pagination
    """
    if request.method == 'POST':
        # Handle AJAX request for more titles
        if session['last_title'] != None:
            books, session['last_title'] = firestore.read_limit(start_after=session['last_title'])
            return jsonify(books)
        return jsonify(None)
    else:
        # Handle initial page load
        books, session['last_title'] = firestore.read_limit()
        return render_template('index.html', books=books)


@bp.route('/add', methods=['GET', 'POST'])
def add_book():
    """Load BookForm to add a book to the database"""
   
    form = BookForm()

    if form.validate_on_submit():
        data = clean_form_data(form.data)
        # If an image was uploaded, update the data to point to the new image.
        image_url = upload_image_file(request.files.get('cover_img'))
        if image_url != None:
            data['cover_img'] = image_url
        else:
            data['cover_img'] = ''
        book = firestore.create(data)
        return redirect(url_for('books.book_view', book_id=book['id']))
    return render_template('book_form.html', form=form, book={})


@bp.route('/update/<book_id>', methods=['GET', 'POST'])
def update(book_id):
    """Load BookForm with book information to edit book information in the database"""
    book = firestore.read(book_id, False)
    form = BookForm(data=book)

    if form.validate_on_submit():
        data = clean_form_data(form.data)
        # If an image was uploaded, update the data to point to the new image.
        image_url = upload_image_file(request.files.get('cover_img'))
        if image_url != None:
            data['cover_img'] = image_url
        else:
            data['cover_img'] = book['cover_img']
        book = firestore.update(clean_form_data(data), book['id'])
        return redirect(url_for('books.book_view', book_id=book['id']))
    if book['cover_img'] != '':
        book['cover_img'] = book['cover_img'].rsplit('/', 1)[1]
    return render_template('book_form.html', form=form, book=book)


@bp.route('/book/<book_id>', methods=['GET'])
def book_view(book_id):
    """Load page to view induvidual book information"""
    book = firestore.read(book_id)
    return render_template('book_view.html', book=book)


@bp.route('/delete/<book_id>', methods=['GET'])
def delete(book_id):
    """Delete the book from the database"""
    firestore.delete(book_id)
    return redirect(url_for('books.index'))

@bp.route('/delete_cover', methods=['POST'])
def delete_cover():
    book_id = request.form.get('book_id')

    book = firestore.read(book_id)

    cover_filename = book['cover_img'].rsplit('/', 1) [1]

    firestore.delete_cover(book_id)
    storage.delete_cover(cover_filename)
    return jsonify('')
    #return redirect(url_for('books.book_view', book_id=book_id))


@bp.route('/test_post', methods=['POST'])
def test_post():
    book_id = request.form.get('book_id')
    print(book_id)
    return jsonify('')
    

app/templates/base.html
<!DOCTYPE html>
    <html>
        <head>
            <!--Import Google Icon Font-->
            <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
            <!-- Compiled and minified CSS -->
            <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
            
        
            <style>{% block style %}{% endblock %}</style>
          
            <title>{% block title %}{% endblock %}</title>
            <!--Let browser know website is optimized for mobile-->
            <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        </head>

        <body>
            <nav>
                <div class="nav-wrapper container">
                  <a href="{{ url_for('books.index') }}" class="brand-logo">Bookshelf</a>
                  <ul class="right hide-on-med-and-down">
                    <li><a href="{{ url_for('books.add_book') }}">Add Book</a></li>
                    <li><a href="{{ url_for('books.index') }}">Books</a></li>
                  </ul>
                  <ul id="nav-mobile" class="sidenav">
                    <a href="{{ url_for('books.index') }}" class="red lighten-2">Bookshelf</a>
                    <!--<a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>-->
                    <li><a href="{{ url_for('books.add_book') }}">Add Book</a></li>
                    <li><a href="{{ url_for('books.index') }}">Books</a></li>
                  </ul>
                  <a href="#" data-target="nav-mobile" class="sidenav-trigger">
                    <i class="material-icons">menu</i>
                  </a>
                </div>
              </nav>
            
            
                {% block content %}{% endblock %}
            
            <!--JavaScript at end of body for optimized loading-->
            <!-- Compiled and minified JavaScript -->
            <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
            <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
            <script>
                document.addEventListener('DOMContentLoaded', function() {
                   var elems = document.querySelectorAll('.sidenav');
                   var instances = M.Sidenav.init(elems);
                 });
               
                 // Initialize collapsible (uncomment the lines below if you use the dropdown variation)
                 // var collapsibleElem = document.querySelector('.collapsible');
                 // var collapsibleInstance = M.Collapsible.init(collapsibleElem, options);
               
               
               </script>
            {% block scripts %}{% endblock %}
            {% block mobile %}{% endblock %}
        </body>
    </html>

app/templates/book_form.html
{% extends "base.html" %}

{% block content %}

    <div class="container">
    <h4>Book Form</h4>
    <div class="row">
        <form method="post" class="col s12" enctype="multipart/form-data">
            {{ form.hidden_tag() }}

            <div class="row">
                <div class="input-field col s12">
                    {{ form.title() }}
                    {{ form.title.label }}
                </div>
            </div>

            <div class="row">
                <div class="input-field col s12">
                    {{ form.author() }}
                    {{ form.author.label }}
                </div>
            </div>

            <div class="row">
                <div class="input-field col s12">
                    {{ form.publication_date(class="datepicker") }}
                    {{ form.publication_date.label }}
                </div>
            </div>

            <div class="row">
                <div class="input-field col s12">
                    {{ form.description(class="materialize-textarea") }}
                    {{ form.description.label }}
                </div>
            </div>

            <div class="row">
                <div class="file-field input-field col s8">
                    <div class="btn">
                        <span>File</span>
                        {{ form.cover_img(value="{{ book.cover_img }}", id="cover_file") }}
                    </div>
                    <div class="file-path-wrapper">
                        <input id=cover_url class="file-path validate" type="text" value="{{ book.cover_img }}">
                    </div>  
                </div>
                <div class="col s4">
                    
                    {% if book.cover_img != "" %}   
                        <div class="delete-img">
                            <!--<a href="{{ url_for('books.delete_cover', book_id=book['id']) }}">-->
                                <i class="material-icons del-cover" id="{{ book['id'] }}"">delete</i>
                            <!--</a>-->
                        </div>    
                    {% endif %}     
                </div>
            </div>

            <div class="row">
                <div class="col s12">
                    <button class="btn waves-effect waves-light" type="submit" name="action">Submit
                        <i class="material-icons right">send</i>
                      </button>
                </div>
                
            </div>
        </form>
    </div>
</div>


{% endblock %}

{% block scripts %}
<script>
  document.addEventListener('DOMContentLoaded', function() {
    var elems = document.querySelectorAll('.datepicker');
    var instances = M.Datepicker.init(elems, {
        format: 'mm/dd/yyyy'});
  });
</script>

<script>
    document.addEventListener('DOMContentLoaded', function() {
        var elements = document.getElementsByClassName("del-cover");

        for (var i=0; i < elements.length; i++) {
            var book_id = elements[i].id;
            elements[i].addEventListener('click', function(){
                
                var xhttp = new XMLHttpRequest;
                xhttp.onreadystatechange = function() {
                    if (this.readyState == 4 && this.status == 200) {
                        document.getElementById("cover_file").value = '';
                        document.getElementById("cover_url").value = '';
                    }
                }
                xhttp.open("POST", "{{ url_for('books.delete_cover') }}", true);
                xhttp.setRequestHeader("Content-type", "application/x-www-form-urlencoded");
                xhttp.send("book_id="+book_id);
            }, false);
        };
    });
</script>

  {% endblock %}

app/templates/book_view.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h4>Book</h4>
    <div class="btn-group">
        <a href="{{ url_for('books.update', book_id=book['id']) }}" class="waves-effect waves-light btn">Edit</a>
        <a href="{{ url_for('books.delete', book_id=book['id']) }}"class="waves-effect waves-light red lighten-2 btn">Delete</a>
    </div>
    
    
    <div class="col s12 m8 offset-m2 l6 offset-l3">
        <div class="card-panel grey lighten-5 z-depth-1">
          <div class="row valign-wrapper">
            <div class="col s12 m2">
            {% if book['cover_img'] %}
                <img src="{{ book['cover_img'] }}" alt="" class="responsive-img">
            {% else %}
                <img src="https://via.placeholder.com/150" alt="" class="responsive-img">
            {% endif %}
            </div>
            <div class="col s12 m10">
              <span class="black-text">
                <h5>{{ book['title'] }}</h5>
                <p><span class="">{{ book['publication_date'] }}</span><br>
                    {{ book['author'] }}<br>
                    {{ book['description'] }}</p>              
              </span>
            </div>
          </div>
        </div>
      </div>
</div>
    


{% endblock %}

app/templates/index.html
{% extends "base.html" %}

{% block content %}
    <div id="list-content" class="container">
        {% for book in books %}
            <div class="col s12 m8 offset-m2 l6 offset-l3">
                <div class="card-panel grey lighten-5 z-depth-1">
                    <div class="row valign-wrapper">
                        <div class="col s12 m2">
                            {% if book['cover_img'] %}
                                <a href="{{ url_for('books.book_view', book_id=book['id']) }}"><img src="{{ book['cover_img'] }}" alt="" class="responsive-img" style="width:150px;height:150px;"></a>
                            {% else %}
                                <a href="{{ url_for('books.book_view', book_id=book['id']) }}"><img src="https://via.placeholder.com/150" alt="" class="responsive-img"></a>
                                
                            {% endif %}
                        </div>
                        <div class="col s12 m10">
                            <span class="black-text">
                                <h5><a href="{{ url_for('books.book_view', book_id=book['id']) }}">{{ book['title'] }}</a></h5>
                                <p><span class="">{{ book['publication_date'] }}</span><br>
                                {{ book['author'] }}<br>
                                {{ book['description'] }}</p>              
                            </span>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
        {% if last_title %}
        <div class="pager">            
            <a href="?start_after={{ last_title }}" class="waves-effect waves-light btn">Load More</a>
        </div>
        {% endif %}

        <!-- Floating Add-->
        <div class="fixed-action-btn">
            <a href="{{ url_for('books.add_book') }}" class="btn-floating btn-large red lighten-2">
              <i class="large material-icons">add</i>
            </a>
          </div>
    </div>
{% endblock %}

{% block scripts %}
<script>
    document.addEventListener('DOMContentLoaded', function() {
        var elems = document.querySelectorAll('.fixed-action-btn');
        var instances = M.FloatingActionButton.init(elems);
    });
</script>

<script>
    $(document).ready(function(){
        $( window ).scroll(function() {
            var lastTitle = "{{ last_title }}";
            var container = document.getElementById("list-content");
            var bottom = document.body.scrollHeight - window.innerHeight;
            
            if (document.body.scrollTop == bottom || document.documentElement.scrollTop == bottom) {
                $.post("{{ url_for('books.index') }}", 
                    function(data){
                        if (data){
                            for (book of data){
                                var baseURL = "{{ url_for('books.book_view', book_id='') }}";
                                var bookId = book.id;
                                var viewURL = baseURL + bookId;
                                //var viewURL= book.id;
                                if (book.cover_img){
                                    bookCoverPath = `<a href="` + viewURL +`"><img src="` + book.cover_img + `" alt="" class="responsive-img" style="width:150px;height:150px;"></a>`
                                }else{
                                    bookCoverPath =`<a href="` + viewURL +`"><img src="https://via.placeholder.com/150" alt="" class="responsive-img"></a>`
                                };
                                htmlString = `<div class="col s12 m8 offset-m2 l6 offset-l3">
                                    <div class="card-panel grey lighten-5 z-depth-1">
                                        <div class="row valign-wrapper">
                                            <div class="col s12 m2">` +
                                                bookCoverPath +
                                            `</div>
                                            <div class="col s12 m10">
                                                <span class="black-text">
                                                    <h5><a href="#">` + book.title + `</a></h5>
                                                    <p><span class="">` + book.publication_date + `</span><br>`
                                                    + book.author + `<br>`
                                                    + book.description + `</p>              
                                                </span>
                                            </div>
                                        </div>
                                    </div>
                                </div>`;
                                container.innerHTML += htmlString;     
                            };
                        };                        
                    }, "json");
                }
            });
        });
</script>
{% endblock %}

app/templates/upload.html
{% extends "base.html" %}

{% block content %}

<div class="container">
        <h4>Upload Form</h4>
    <div class="row">
        <form method="post" class="col s12" enctype=multipart/form-data>
            {{ form.hidden_tag() }}

            <div class="row">
                <div class="input-field col s12">
                    {{ form.title() }}
                    {{ form.title.label }}
                </div>
            </div>

            <div class="row">
                <div class="input-field col s12">
                    {{ form.author() }}
                    {{ form.author.label }}
                </div>
            </div>

            <div class="row">
                <div class="input-field col s12">
                    {{ form.publication_date(class="datepicker") }}
                    {{ form.publication_date.label }}
                </div>
            </div>

            <div class="row">
                <div class="input-field col s12">
                    {{ form.description(class="materialize-textarea") }}
                    {{ form.description.label }}
                </div>
            </div>

            <div class="row">
                <div class="file-field input-field col s12">
                    <div class="btn">
                        <span>File</span>
                        {{ form.cover_img() }}
                    </div>
                    <div class="file-path-wrapper">
                        <input class="file-path validate" type="text">
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col s12">
                    <button class="btn waves-effect waves-light" type="submit" name="action">Submit
                        <i class="material-icons right">send</i>
                    </button>
                </div>
            </div>
        </form>
    </div>
</div>  
{% endblock %}

{% block scripts %}
<script>
  document.addEventListener('DOMContentLoaded', function() {
    var elems = document.querySelectorAll('.datepicker');
    var instances = M.Datepicker.init(elems, {
        format: 'mm/dd/yyyy'});
  });
</script>

  {% endblock %}